<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<WarnOn>3390;$(WarnOn)</WarnOn>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>


	<ItemGroup>
		<Reference Include="SolidWorks.Interop.sldworks">
			<HintPath>C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll</HintPath>
			<EmbedInteropTypes>False</EmbedInteropTypes>
			<Private>False</Private>
		</Reference>
		<Reference Include="SolidWorks.Interop.swconst">
			<HintPath>C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll</HintPath>
			<EmbedInteropTypes>False</EmbedInteropTypes>
			<Private>False</Private>
		</Reference>
		<Reference Include="SolidWorks.Interop.swpublished">
			<HintPath>C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swpublished.dll</HintPath>
			<EmbedInteropTypes>False</EmbedInteropTypes>
			<Private>False</Private>
		</Reference>
		<Reference Include="SolidWorks.Interop.SWRoutingLib">
			<HintPath>C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.SWRoutingLib.dll</HintPath>
			<Private>False</Private>
			<EmbedInteropTypes>False</EmbedInteropTypes>
		</Reference>
		<Reference Include="SolidWorksTools">
			<HintPath>C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\solidworkstools.dll</HintPath>
			<EmbedInteropTypes>False</EmbedInteropTypes>
			<Private>False</Private>
		</Reference>
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>




	<ItemGroup>
		<Compile Include="Clipboard.fs" />
		<Compile Include="CommandManagerUtils.fs" />
		<Compile Include="CommandItemCollection.fs" />
		<Compile Include="SysUserPreference.fs" />
		<Compile Include="DocUserPreference.fs" />
		<Compile Include="RoutingUserPreference.fs" />
		<Compile Include="CommentUtils.fs" />
		<Compile Include="CustomInfoType.fs" />
		<Compile Include="CustomPropertyManagerUtils.fs" />
		<Compile Include="ParameterUtils.fs" />
		<Compile Include="AttributeUtils.fs" />
		<Compile Include="AttributeDefUtils.fs" />
		<Compile Include="CalloutUtils.fs" />
		<Compile Include="EntityUtils.fs" />
		<Compile Include="Body2Utils.fs" />
		<Compile Include="Face2Utils.fs" />
		<Compile Include="Loop2Module.fs" />
		<Compile Include="EdgeUtils.fs" />
		<Compile Include="CurveUtils.fs" />
		<Compile Include="SketchManagerUtils.fs" />
		<Compile Include="SelectionMgrUtils.fs" />
		<Compile Include="FeatureManagerUtils.fs" />
		<Compile Include="FeatureExtrusion3.fs" />
		<Compile Include="FeatureUtils.fs" />
		<Compile Include="FeatureNode.fs" />
		<Compile Include="MathUtilityUtils.fs" />
		<Compile Include="MathPointUtils.fs" />
		<Compile Include="Component2Utils.fs" />
		<Compile Include="ConfigurationUtils.fs" />
		<Compile Include="AddComponent5Params.fs" />
		<Compile Include="AddMate5Params.fs" />
		<Compile Include="AssemblyDocUtils.fs" />
		<Compile Include="PartDocUtils.fs" />
		<Compile Include="ModelDoc2Utils.fs" />
		<Compile Include="SldWorksUtils.fs" />
		<Compile Include="DocActivator.fs" />
		<Compile Include="ModelSpecific.fs" />
		<Compile Include="ComponentModel.fs" />
		<Compile Include="ComponentArchive.fs" />
		<Compile Include="ComponentArchiveJson.fs" />
		<Compile Include="OpenDocExecutor.fs" />
		<Compile Include="CutList.fs" />
		<Compile Include="MathUtilityExtend.fs" />
		<Compile Include="Polar.fs" />
	</ItemGroup>




	<ItemGroup>
	  <PackageReference Include="FSharp.Idioms" Version="1.4.21" />
	  <PackageReference Include="UnquotedJson" Version="1.0.21" />
	</ItemGroup>




	<ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="8.0.301" />
	</ItemGroup>




</Project>
